#!/bin/sh
set -e
# Build for Intel x86_64
make clean
VERBOSE=1 CC=clang CFLAGS="$CFLAGS -arch x86_64 -DFULL_INTERNAL_DATA" LDFLAGS="-lcurl" DNS_PARSER=internal make -j1
mv bin/vlmcs vlmcs-x86_64
mv bin/vlmcsd vlmcsd-x86_64

# Build for Apple Silicon arm64
make clean
VERBOSE=1 CC=clang CFLAGS="$CFLAGS -arch arm64 -DFULL_INTERNAL_DATA" LDFLAGS="-lcurl" DNS_PARSER=internal make -j1
mv bin/vlmcs vlmcs-arm64
mv bin/vlmcsd vlmcsd-arm64
