#!/bin/sh
make clean
VERBOSE=1 CC=gcc CFLAGS="$CFLAGS -static -DFULL_INTERNAL_DATA -D_GNU_SOURCE" LDFLAGS="-static /usr/lib/x86_64-linux-gnu/libpthread.a"  GETIFADDRS=musl DNS_PARSER=internal make -j1
#cp etc/vlmcsd.ini  etc/vlmcsd.kmd bin/
