name: Build with visual studio

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Setup MSVC v141_xp
      uses: ilammy/msvc-dev-cmd@v1
      with:
        toolset: 14.16
        arch: x64

    - name: Install xp tools
      run: |
        "C:\Program Files (x86)\Microsoft Visual Studio\Installer\setup.exe\" modify --add Microsoft.VisualStudio.Component.WinXP --quiet --installPath \"C:\Program Files\Microsoft Visual Studio\2019\BuildTools"

    - name: Build solution
      run: msbuild VisualStudio/vlmcsd-windows.sln /p:Configuration=Release /p:Platform=x64

    - name: Zip release
      run: Compress-Archive -Path bin/* -DestinationPath bin/release.zip

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload R    elease Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./bin/release.zip
        asset_name: release.zip
        asset_content_type: application/zip